### PR TITLE
TypeError: Descriptors should not be created directly, but only retrieved from their parent.

### PR DESCRIPTION
**Pull request by rafaelsilverioit**
Fixing error related to newer protobuf code that checks if generated protocol files have the '_pb2.py' suffix in their names.

Error message:
```
File "/usr/lib/python2.7/dist-packages/google/protobuf/descriptor.py", line 501, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors should not be created directly, but only retrieved from their parent.
```
Briefly, renaming the generated protbuf files fixes the issue. Detailed information on this issue is available in #14 under [Antonio's](https://github.com/tgalal/python-axolotl/issues/14#issue-173164517) message.

### CODE REVIEW

**Comment by ao2** [comment]
@rafaelsilverioit thanks, but please don't take over patches, if you really want to propose a pull request just `git am` my original patch (https://bugs.debian.org/cgi-bin/bugreport.cgi?att=1;bug=835271;filename=0001-Keep-the-_pb2-suffix-in-the-name-for-protobuf-genera.patch;msg=22), this way I get attribution; that patch also has a batter commit message IMHO.

I spend quite some time writing commit messages and it's a waste to see them lost :)

BTW I didn't propose this as a pull request originally because I was also asking the author **how** he wanted the issue to be fixed, it was in the last part of my original comment.

Thanks again,
   Antonio

**Comment by rafaelsilverioit** [comment]
@ao2 I did not knew about `git am`, thank you!

I have applied your original patch and merged it to my master branch.

**Comment by ao2** [comment]
@rafaelsilverioit another couple of tips if I may:
* no need to add the `.patch` file to the code repository
* try working in a separate branch (call it "keep-pb2-suffix" for example), add the changes to the new branch and send pull request from that branch, not from your master branch, this is the recommended practice in git. This way you keep your master branch clean and you can easily fast-forward it if needed when the upstream updates their master branch.

**Comment by tgalal** [comment]
@rafaelsilverioit thanks a lot

@ao2 cherrypicked your patch from @rafaelsilverioit's changes. Sorry it took me too long.

**Pull request closed without merging**
